development:
  adapter: mysql2
  database: vatatis_development
  pool: 5
  username: vatatis
  password:
test:
  adapter: mysql2
  database: vatatis_test
  pool: 5
  username: vatatis
  password:
production:
  adapter: mysql2
  database: vatatis_production
  pool: 5
  username: vatatis
  password:
