development:
  adapter: sqlite3
  database: vatatis_development
  pool: 5
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: vatatis_test
  pool: 5
  database: db/test.sqlite3
production:
  adapter: mysql2
  database: CHANGE
  username: CHANGE
  password: CHANGE
  pool: 5
