development:
  adapter: sqlite3
  database: vatatis_development
  pool: 5
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: vatatis_test
  pool: 5
  database: db/test.sqlite3
production:
  adapter: sqlite3
  database: vatatis_production
  pool: 5
  database: db/production.sqlite3
